version: "3.8"
services:
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.backend
    ports:
      - "4000:4000"
  agent:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.agent
    volumes:
      - ./data:/data
