server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

storage:
  data_dir: "./data"
  max_file_size: 104857600  # 100MB
  chunk_size: 1024          # 1KB chunks
  temp_dir: "./temp"
  cleanup_period: "1h"

logging:
  level: "info"
  format: "json"
  output: "stdout"

network:
  indexer_endpoint: "https://indexer.0g.ai"
  transfer_endpoint: "https://transfer.0g.ai"
  core_endpoint: "https://core.0g.ai"
  rpc_url: "https://evmrpc-testnet.0g.ai"
  chain_id: 16601
  contract_address: "0xd332ABE4395c5173E04F4cbBF39DB175C23ad0eC"
  private_key: "31cf0f5d515e3121ef1e48c2bf528c40acc22c6415a1027c304fa3064b3ddab8"
  timeout: "30s"
  retry_attempts: 3
  retry_delay: "5s"

security:
  enable_tls: false
  cert_file: ""
  key_file: ""
  allowed_hosts: []
  rate_limit: 100
  rate_limit_window: "15m"
